version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.2
    volumes:
      - ./database:/data/db
    restart: always

  server:
    container_name: server
    build: ./backend
    restart: always
    depends_on:
      - mongodb

  nginx:
    container_name: nginx
    build: ./frontend
    restart: always
    ports:
      - 13000:80
